name: delightsome_software
description: "Delightsome Inventory Software"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  expandable_group: ^0.0.5
  collection: ^1.18.0
  fluttertoast: ^8.2.4
  provider: ^6.1.1
  intl: ^0.19.0
  flutter_launcher_icons: "^0.13.1"
  month_year_picker2: ^1.0.0+2
  sticky_grouped_list: ^3.1.0
  shared_preferences: ^2.2.2
  http: ^1.1.2
  hive_flutter: ^1.1.0
  universal_html: ^2.2.4
  socket_io_client: ^3.0.0
  printing: ^5.13.3
  htmltopdfwidgets: ^1.0.4
  indexed: ^0.0.8
  linked_scroll_controller: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
